#!/bin/bash

rm -f ../docs/status/dashboard.*
rm -f *.txt
cat ../docs/status/template.tex  > ../docs/status/dashboard.tex

../scripts/tcregrtst -d model

input_file1="model_reg.log"
IT=1
LC=1
while IFS= read -r line1; do
    gawk '{print $4 " & " $3 " & "}' <<< "$line1" | sed 's/_/\\_/g' > $IT.txt;
    IT=$(($IT+1));
    LC=$(($LC+1));
done < "$input_file1"

../scripts/tcregrtst -d beh

input_file2="beh_reg.log"
IT=1
while IFS= read -r line2; do
    (gawk '{print $3 " & "}' <<< "$line2" | sed 's/_/\\_/g') >> $IT.txt;
    IT=$(($IT+1));
done < "$input_file2"

../scripts/tcregrtst -d str

input_file3="str_reg.log"
IT=1
while IFS= read -r line3; do
    (gawk '{print $3 " \\\\ "}' <<< "$line3" | sed 's/_/\\_/g') >> $IT.txt;
    echo "\hline" >> $IT.txt;
    IT=$(($IT+1));
done < "$input_file3"
FILES=$(ls *.txt)
for file in $FILES; do
    tr -d '\n' < $file > new${file}
    cat new${file} >> ../docs/status/dashboard.tex;
    echo -e "\n" >> ../docs/status/dashboard.tex;
done
echo "\end{tabular} \end{table} \end{document}" >> ../docs/status/dashboard.tex
if command -v latexmk &>/dev/null; then
    echo "latexmk is installed"
else
    echo "latexmk is not installed, install it then run the script. Fatal."
    exit 34;
fi
latexmk -pdf ../docs/status/dashboard.tex
if [ $? -eq 0 ]; then
    echo "latexmk succeeded"
else
    echo "latexmk failed, error in input .tex file. Pdf not built."
    exit 33;
fi
