#!/bin/bash
TEST_DIR=../prog/src/
TESTS=$(ls $TEST_DIR)
DESIGN=$2

BRIEF_HELP="A simple tool that regression tests and compares results of emu design against either one of the 3 (model or beh, str or str74) and provides a short report on the same. Use '-h' (--help long form) option to know more about 'tcregtst' tool."
FILL80=| fold -w 80 -s

if [[ $1 == "" ]] ; then
    printf "%-80s\n" "${BRIEF_HELP}" | fold -w 80 -s;
    exit 0;
fi
rm -f ${DESIGN}_reg.log
exec 2> regrerror.log
VALID_ARGS=$(getopt --options d:h --long design:,help -- "$@")
if [[ -s regrerror.log ]] ; then                       #-s returns true if file exists with size greater than zero otherwise false
    echo -e "regrerror.log is non empty, hence error has occured in getopt\nstage, fatal.";
    exit 3;
# else echo -e "regrerror.log is empty hence no error has occured in getopt stage, continuing." | fold -w 80 -s;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
    case "$1" in
        -d | --design)
            if [[ $2 == "model" ]] || [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
                DESIGN=$2
                OUTNAME=$2.out;
            else echo -e "The above value '$2' for --design/-d option is invalid,\nuse -h or --help to know more about the option --design values.";
                 echo -e "Error: test failed due to invalid design name.\nTest+Design specific log file not produced.\nFatal." > regrerror.log
                 exit 10;
            fi
            shift 2
            ;;
        -h | --help)
            echo -e "'tcregtst' script allows you to test a particular design (beh or str or str74) using all tests in the directory ../prog/src/ against the emu reference design, it needs an argument -d and an argument that is among the mentioned 3 designs above (model or beh or str or str74), it generates a design_reg.log file along with a regrerror.log file, the first one contains information regarding all passing/failing of all the tests." | fold -w 80 -s
	    exit 1;
            shift
            ;;
        --) shift;
            break
            ;;
    esac
done

eval set "" $TESTS	    
while [[ $1 != "" ]]; do
    # echo "$1";
    if [[ $1 != *.s ]] ; then
        shift;
        continue;
    fi
    ../scripts/tctst -d $DESIGN $1;
    if [[ -s error.log ]] ; then
	echo -e "${DESIGN} design failed ${1} test" >> ${DESIGN}_reg.log;
	cat error.log >> regrerror.log;
	echo -e "\n" >> regrerror.log;
	# find . -type f -not -name '.gitignore' -not -name "${DESIGN}_reg.log" -not -name "regrerror.log" -exec rm -f {} +;
	shift;
	continue;
    fi
    TESTNAME=$(gawk -F '.' '{ print $1 }' <<< $1);
    cat ${DESIGN}_${TESTNAME}.log >> ${DESIGN}_reg.log;
    rm -f ${DESIGN}_${TESTNAME}.log
    find . -type f -not -name '.gitignore' -not -name "*.txt" -not -name "${DESIGN}_reg.log" -not -name "regrerror.log" -exec rm -f {} +
	shift;
done
