#!/bin/bash
TEST_DIR=../prog/src/
TESTS=$(ls $TEST_DIR)
DESIGN=$1

BRIEF_HELP="A simple tool that regression tests and compares results of emu design against either one of the 3 (beh, str or str74) and provides a short report on the same. Use '-h' (--help long form) option to know more about 'tcregtst' tool."
FILL80=| fold -w 80 -s

if [[ $1 == "" ]] ; then
    printf "%-80s\n" "${BRIEF_HELP}" | fold -w 80 -s;
    exit 0;
fi
exec 2> regrerror.log
VALID_ARGS=$(getopt --options d:h --long design:,help -- "$@")
if [[ -s regrerror.log ]] ; then                       #-s returns true if file exists with size greater than zero otherwise false
    echo -e "regrerror.log is non empty, hence error has occured in getopt\nstage, fatal.";
    exit ;
# else echo -e "regrerror.log is empty hence no error has occured in getopt stage, continuing." | fold -w 80 -s;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
    case "$1" in
        -d | --design)
            if [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
                DESIGN=$2
                OUTNAME=$2.out;
            else echo -e "The above value '$2' for --design/-d option is invalid,\nuse -h or --help to know more about the option --design values.";
                 echo -e "Error: test failed due to invalid design name.\nTest+Design specific log file not produced.\nFatal." > regrerror.log
                 exit 10;
            fi
            shift 2
            ;;
        -h | --help)
            echo -e "The use of the script is in the following format - \n../scripts/tctst [option] [option_with argument] argument testname.\nThe script supports 3 options:-\n\n -h (--help) option provides detailed methods of using the tool.If -h option (an argument-less option) is used, then no testname is allowed.\n\n -D (--DEBUG long format) - This option enables the debug mode in the SRAM  module, the debug messages (SRAM I/O values) are stored in 'design'_'testname'.trace file.\n\n -d (--design long format) - This option requires an argument that must be one of the following three choices\n a) beh - Behavioural Model\n b) str - Structural Model\n c) str74 - Structural in 74 Model\nIn absence of -h (--help) option, a testfile should be provided which is present in the directory ../prog/src/ and should be an Assembly code file adhering to Instruction Format specified in specs doc." | fold -w 80 -s
	    exit 0;
            shift
            ;;
        --) shift;
            break
            ;;
    esac
done

eval set "" $TESTS	    
while [[ $1 != "" ]]; do
    echo "$1";
    ../scripts/tctst -d $DESIGN $1;
    if [[ -s error.log ]] ; then
	echo -e "${DESIGN} design failed ${1}.s test" >> ${DESIGN}_reg.log;
	continue;
    fi
    TESTNAME=$(gawk -F '.' '{ print $1 }' <<< $1);
    cat ${DESIGN}_${TESTNAME}.log >> ${DESIGN}_reg.log;
    rm -f ${DESIGN}_${TESTNAME}.log
    find . -type f -not -name '.gitignore' -not -name "${DESIGN}_reg.log" -exec rm -f {} +
	shift;
done

