#!/bin/bash

ASM=../prog/asm/asm
EMU=../prog/emu/emu
TEST_DIR=../prog/src/
if [[ -n $1 ]]; then
    if [[ $1 == "-h" ]]; then
	echo -e "This script supports cases of no options, --design option and -h option, When run using no options, it would display basic function and method of usage of the script. The -h option provides detailed use cases of the script. The --design should be followed by a valid test source code name. Valid indicating that it should be present in the ../prog/src/ directory. There are 3 cases of --design namely beh, str, str74. In the case of --design=beh would indicate the script to test the behavioural model, --design=str would indicate the structural mode and --design=str74 would indicate the structural in 74 series model.\nExample usage is ../scripts/tctst --design=str src_code.s   ";
    else
	case $1 in
	    "--design=beh")
		if test -e $TEST_DIR$2 ; then
		    $ASM $TEST_DIR$2 -o bin.out
		    $EMU bin.out > emulog
		    
		    ../prog/bin2readmemh/bin2readmemh bin.out > program.mem
		    make beh.out -f ../scripts/Makefile 2> beherrorlog
		    if grep -qi -e "error" -e "stop" -e "no such" -e "unable" beherrorlog ; then
		    	echo "Compilation Error detected, test failed, see beherrorlog file for more details, please solve this issue and retry";
			exit 5;
		    fi
		    vvp beh.out -vcd beh.vcd > behtmp
		    tail -n +2 behtmp > rtllog
		    if diff -s emulog rtllog ; then
			echo "rtl passed "$2" test"; 
		    else "rtl failed "$2" test";
		    fi;
		else echo "Invalid Test name, please try again with a valid test";
		fi;;
	    "--design=str")
		if test -e $TEST_DIR$2 ; then
		    $ASM $TEST_DIR$2 -o bin.out
		    $EMU bin.out > emulog
		    
		    ../prog/bin2readmemh/bin2readmemh bin.out > program.mem
		    make struct.out -f ../scripts/Makefile 2> strerrorlog
		    if grep -qi -e "error" -e "stop" -e "no such" -e "unable" strerrorlog ; then
		    	echo "Compilation Error detected, test failed, see beherrorlog file for more details, please solve this issue and retry";
			exit 5;
		    fi
		    vvp struct.out -vcd beh.vcd > structtmp
		    tail -n +2 structtmp > structurallog
		    if diff -s emulog structurallog ; then
			echo "structural passed "$2" test"; 
		    else "structural failed "$2" test";
		    fi;
		else echo "Invalid Test name, please try again with a valid test";
		fi;;
	    "--design=str74")echo "Structural74 is work in progress try a different option";;
	    *)echo "invalid option, supported --design option values are beh, str and str74";;
	esac;	
    fi;
else echo "This script generates log files for both the emulator and behavioural models and compares them against each other to measure correctness for a particular test, the first argument provided should be the test code file that is present in the ../prog/src/ directory, use -h option to know more.";
fi
