#!/bin/bash

ASM=../prog/asm/asm
EMU=../prog/emu/emu
TEST_DIR=../prog/src
DBG=""
TRACE=""
DESIGN=""
USAGE="Usage: tctst [options] testname\n\
       For details do 'tctst -h'"
BRIEF_HELP="A simple tool that tests and compares results of emu \
design against either one of the 3 (beh, str or str74) \
and provides a short report on the same. \
Use '-h' (--help long form) option to know more about \
'tctst' tool."

##FILL80=| fold -w 80 -s

#-------------------------------------------------------------------------------
# If no args, print usage message and exit
#-------------------------------------------------------------------------------
if [[ $1 == "" ]] ; then
    printf "${USAGE}\n"
#    printf "${BRIEF_HELP}\n" | fold -w 80 -s;
    exit 1; # Error exit
fi


# Redirect stderr to error.log
exec 2> error.log

#-------------------------------------------------------------------------------
# Parse command line arguments
#-------------------------------------------------------------------------------
VALID_ARGS=$(getopt --options d:Dh --long design:,debug,help -- "$@")

if [[ -s error.log ]] ; then   #-s returns true if file exists with size greater than zero otherwise false
    echo `cat error.log | sed -e s/getopt/Error/g`
    echo "For help do 'tctst --help'"
    exit 1;
# else echo -e "error.log is empty hence no error has occured in getopt stage, continuing." | fold -w 80 -s;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
    case "$1" in
        -d | --design)
            if [[ $2 == "model" ]] || [[ $2 == "beh" ]] || [[ $2 == "str" ]] || [[ $2 == "str74" ]]; then
                DESIGN=$2
                OUTNAME=$2.out;
            else
                echo -e "Error: Unknown design '$2'. Fatal." | tee error.log
                echo -e "For help do 'tctst --help'.";
                exit 10;
            fi
            shift 2
            ;;
        -D | --debug)
            DBG="_dbg.";
            shift
            ;;
        -h | --help)
            echo -e "The use of the script is in the following format - \n../scripts/tctst [option] [option_with argument] argument testname.\nThe script supports 3 options:-\n\n -h (--help) option provides detailed methods of using the tool.If -h option (an argument-less option) is used, then no testname is allowed.\n\n -D (--debug long format) - This option enables the debug mode in the SRAM  module, the debug messages (SRAM I/O values) are stored in 'design'_'testname'.trace file.\n\n -d (--design long format) - This option requires an argument that must be one of the following three choices\n a) model - Reference Model\n b) beh - Behavioural Model\n c) str - Structural Model\n d) str74 - Structural in 74 Model\nIn absence of -h (--help) option, a testfile should be provided which is present in the directory ../prog/src/ and should be an Assembly code file adhering to Instruction Format specified in specs doc." | fold -w 80 -s
            exit 0;
            shift
            ;;
        --) shift;
            break
            ;;
    esac
done

if [[ $DBG == "" ]] ; then
    DBG="." ;
fi

OUTNAME=$(gawk -F '.' --assign dbg=$DBG '{ print ($1 dbg $2) }' <<< $OUTNAME)

if [[ -s $TEST_DIR/$1 ]]; then
    echo -e "Test name is valid and exists in ../prog/src/ directory";
else echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ directory.\nFatal";
     echo -e "Error: test name is not valid and doesnt exist in ../prog/src/ directory.\nFatal" > error.log;
     exit 11;
fi

TESTNAME=$1
$ASM $TEST_DIR/$TESTNAME -o bin.out | tee error.log
TESTNAME=$(gawk -F '.' '{ print $1}' <<< $TESTNAME)

if [[ -s error.log ]]; then
    echo -e "Error: $TESTNAME test contains errors, please refer to specs doc\nand correct the issue.\nFatal";
    exit 12;
else echo -e "$TESTNAME test code contains no errors, proceeding to next step.";
fi

rm -f debug.trace

$EMU bin.out > emu_${TESTNAME}.trace
../prog/bin2readmemh/bin2readmemh bin.out > program.mem
sleep 0.2
if [[ $TESTNAME".s" == "sort.s" ]] ; then
    ../scripts/sortappend;
fi
make $OUTNAME --makefile=../scripts/makefile

if [[ -s error.log ]]; then
    echo -e "Error: Makefile reported an error, check error.log file for more details.\nFatal";
    exit 13;
fi

vvp $OUTNAME > ${DESIGN}_${TESTNAME}tmp
tail -n +2 ${DESIGN}_${TESTNAME}tmp > ${DESIGN}_${TESTNAME}.trace
rm ${DESIGN}_${TESTNAME}tmp

# if [[ $DBG == "_dbg." ]] ; then
#     echo -e "Debug option enabled, script stopped, debug values\nin ${DESIGN}_${TESTNAME}.trace file"
#     exit 0;
# fi

if diff -q emu_${TESTNAME}.trace ${DESIGN}_${TESTNAME}.trace ; then
    echo -e "${DESIGN} design passed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
    exit 0;
else
    echo -e "${DESIGN} design failed ${TESTNAME}.s test" > ${DESIGN}_${TESTNAME}.log;
    exit 14;
fi
