name: regression test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install iverilog
      - name: Test reference model `model`
        if: success() || failure()
        run: |
          cd run
          ../scripts/tcregrtst -d model
      - name: Test behavioral model `beh`
        if: success() || failure()
        run: |
          cd run
          ../scripts/tcregrtst -d beh
      - name: Test structural model `str`
        if: success() || failure()
        run: |
          cd run
          ../scripts/tcregrtst -d str
