name: regression test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install iverilog tcsh
      - name: Test behavioral model `beh`
        run: |
          cd run
          for f in $(ls ../prog/src); do ../scripts/tctst -d beh $f; done
      - name: Test structural model `str`
        run: |
          for f in $(ls ../prog/src); do ../scripts/tctst -d str $f; done
